-- Small deterministic bootstrap. The production-size dataset is generated by scripts/seed.py.
INSERT INTO coupons(coupon_code,discount_type,discount_value,minimum_order_value,maximum_discount,valid_from,valid_until,usage_limit,is_active)
VALUES ('WELCOME20','PERCENTAGE',20,299,120,current_date-365,current_date+365,10000,true),
       ('FLAT75','FIXED',75,499,75,current_date-365,current_date+365,5000,true),
       ('EXPIRED50','PERCENTAGE',50,200,200,current_date-730,current_date-365,100,false)
ON CONFLICT (coupon_code) DO NOTHING;

